CFLAGS = -fomit-frame-pointer -fno-exceptions -ffast-math -I../core/include -I../common/include -IEngine3D -DMSDOS -DRES128X128 -DTRACE_OBJECTS_OVER_FLOOR -DCAN_PICK_OBJECT_AT_ANY_DISTANCE -DUSE_FILLED_POLYS -DSUPPORTS_ROOM_TRANSITION_ANIMATION -DENDIANESS_AWARE

CC = i386-pc-msdosdjgpp-gcc

OBJS = Engine3D/demo.o MSDOSVersion/msdos.o \
    ../core/src/Core.o \
    ../core/src/Derelict.o \
    ../common/src/PackedFileReader.o \
    ../common/src/CTile3DProperties.o \
    ../common/src/MapWithCharKey.o \
    ../common/src/FixP.o \
    ../common/src/Globals.o \
    ../common/src/Common.o

TARGET = derelict.exe

$(TARGET):	$(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LDFLAGS)

all:	$(TARGET)

clean:
	rm -f Engine3D/*.o
	rm -f MSDOSVersion/*.o
	rm -f ../core/src/*.o
	rm -f ../common/src/*.o