;this file for FamiTone2 library generated by text2data tool

space_radar_menu_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env5,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env3,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$00,$00
@env2:
	.byte $ca,$ce,$cf,$ce,$cd,$02,$cc,$cc,$c9,$03,$c8,$c7,$c7,$c6,$c6,$c4
	.byte $03,$c2,$06,$c1,$04,$c2,$c1,$03,$c1,$00,$13
@env3:
	.byte $cb,$cd,$ce,$cf,$cf,$cd,$ca,$c8,$c7,$c7,$c6,$c6,$c5,$02,$c4,$02
	.byte $c3,$04,$c2,$02,$c1,$0b,$c0,$00,$16
@env4:
	.byte $ce,$cd,$cc,$ca,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$0b
@env5:
	.byte $c2,$c3,$c3,$c5,$c5,$c6,$c6,$c7,$c8,$ca,$cb,$cd,$ce,$03,$cc,$cb
	.byte $ca,$c9,$c7,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$00,$19


@song0ch0:
	.byte $fb,$09
@song0ch0loop:
@ref0:
	.byte $83,$80,$63,$69,$70,$85,$63,$69,$70,$85,$63,$69,$71,$6f,$69,$6f
	.byte $70,$81
@ref1:
	.byte $83,$63,$69,$70,$85,$69,$6f,$70,$85,$61,$67,$71,$6f,$67,$61,$58
	.byte $81
@ref2:
	.byte $83,$63,$69,$70,$85,$63,$69,$70,$85,$63,$69,$71,$6f,$69,$6f,$70
	.byte $81
@ref3:
	.byte $83,$63,$67,$68,$85,$67,$69,$6c,$85,$69,$6d,$71,$6d,$67,$61,$58
	.byte $81
	.byte $ff,$11
	.word @ref2
	.byte $ff,$11
	.word @ref1
@ref6:
	.byte $83,$63,$69,$70,$85,$63,$69,$70,$85,$61,$67,$71,$6d,$69,$6d,$70
	.byte $81
@ref7:
	.byte $83,$61,$67,$70,$85,$67,$6d,$62,$85,$63,$69,$62,$91
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $82,$50,$00,$51,$4b,$50,$a1,$58,$8d
@ref9:
	.byte $56,$95,$50,$85,$4e,$8d,$48,$89,$00,$81
@ref10:
	.byte $50,$00,$51,$4b,$50,$a1,$58,$8d
@ref11:
	.byte $5a,$95,$54,$85,$60,$99,$00,$81
	.byte $ff,$08
	.word @ref10
	.byte $ff,$0a
	.word @ref9
@ref14:
	.byte $50,$00,$51,$4b,$50,$89,$4a,$85,$48,$95,$40,$85
@ref15:
	.byte $42,$8d,$40,$89,$4b,$00,$9d
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $84,$20,$00,$21,$1b,$20,$85,$1b,$21,$1b,$20,$00,$21,$1b,$20,$85
	.byte $1b,$21,$1a,$81
@ref17:
	.byte $20,$00,$21,$1b,$20,$85,$1b,$21,$1b,$29,$00,$29,$00,$28,$00,$27
	.byte $00,$27,$00,$26,$00
@ref18:
	.byte $20,$00,$21,$1b,$20,$85,$1b,$21,$1b,$20,$00,$21,$1b,$20,$85,$1b
	.byte $21,$1a,$81
@ref19:
	.byte $25,$00,$25,$00,$25,$27,$00,$27,$00,$27,$29,$00,$29,$00,$29,$10
	.byte $00,$10,$00,$10,$28,$40,$58
	.byte $ff,$13
	.word @ref18
	.byte $ff,$15
	.word @ref17
	.byte $ff,$13
	.word @ref18
@ref23:
	.byte $20,$00,$21,$1b,$21,$01,$1f,$01,$1b,$00,$9d
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $85,$86,$1a,$88,$04,$8b,$86,$1a,$88,$04,$86,$1b,$1a,$85,$1a,$88
	.byte $04,$8b,$86,$1a,$88,$05,$86,$0a,$0c
@ref25:
	.byte $85,$1a,$88,$04,$8b,$86,$1a,$88,$04,$86,$1b,$1a,$85,$1a,$88,$04
	.byte $89,$07,$20,$02,$04,$06
	.byte $ff,$10
	.word @ref24
	.byte $ff,$11
	.word @ref25
	.byte $ff,$10
	.word @ref24
	.byte $ff,$11
	.word @ref25
	.byte $ff,$10
	.word @ref24
@ref31:
	.byte $85,$1a,$88,$04,$8b,$86,$1a,$88,$04,$86,$1b,$1a,$85,$88,$1c,$05
	.byte $1c,$05,$06,$07,$20,$02,$04,$06
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $bf
@ref33:
	.byte $bf
@ref34:
	.byte $bf
@ref35:
	.byte $bf
@ref36:
	.byte $bf
@ref37:
	.byte $bf
@ref38:
	.byte $bf
@ref39:
	.byte $bf
	.byte $fd
	.word @song0ch4loop
