;this file for FamiTone2 library generated by text2data tool

Space_Radar_2_1_3_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $03
	.word @env1,@env7,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env3,@env8,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env9,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env5,@env7,@env0
	.byte $00
	.byte $b0 ;instrument $07
	.word @env6,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cf,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	.byte $c9,$00,$00
@env3:
	.byte $cf,$05,$c0,$00,$02
@env4:
	.byte $cf,$02,$c0,$00,$02
@env5:
	.byte $cf,$02,$ce,$cb,$cb,$c9,$c6,$c5,$c3,$c2,$c1,$c0,$00,$0b
@env6:
	.byte $c6,$c8,$c9,$02,$ca,$03,$c9,$03,$c8,$c8,$c7,$02,$c6,$03,$c5,$03
	.byte $c4,$03,$c3,$04,$c2,$06,$c1,$05,$c1,$00,$18
@env7:
	.byte $c0,$08,$c1,$02,$c0,$02,$c1,$02,$c0,$02,$c0,$00,$02
@env8:
	.byte $c0,$bf,$bc,$b4,$b3,$b0,$00,$05
@env9:
	.byte $c0,$bf,$bc,$00,$02


@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $00,$dd
@ref1:
	.byte $df
@ref2:
	.byte $00,$dd
@ref3:
	.byte $df
@ref4:
	.byte $00,$dd
@ref5:
	.byte $df
@ref6:
	.byte $00,$dd
@ref7:
	.byte $df
@ref8:
	.byte $00,$dd
@ref9:
	.byte $df
@ref10:
	.byte $80,$5b,$55,$5b,$54,$99,$5b,$55,$5b,$55,$5b,$54,$99,$5b,$54,$81
@ref11:
	.byte $5f,$55,$5f,$54,$99,$5f,$55,$63,$59,$63,$59,$63,$59,$53,$4b,$53
	.byte $4b,$53,$58,$81
@ref12:
	.byte $5b,$55,$5b,$54,$99,$5b,$55,$5b,$55,$5b,$54,$99,$5b,$54,$81
	.byte $ff,$14
	.word @ref11
	.byte $ff,$0f
	.word @ref12
	.byte $ff,$14
	.word @ref11
	.byte $ff,$0f
	.word @ref12
@ref17:
	.byte $5f,$55,$5f,$54,$99,$5f,$55,$63,$59,$63,$59,$63,$59,$53,$4b,$53
	.byte $4a,$85,$00,$81
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref18:
	.byte $00,$dd
@ref19:
	.byte $df
@ref20:
	.byte $00,$89,$82,$24,$95,$28,$89,$2a,$a1,$32,$89
@ref21:
	.byte $2e,$95,$24,$ad,$22,$95
@ref22:
	.byte $00,$89,$24,$95,$28,$89,$2a,$95,$32,$95
@ref23:
	.byte $36,$a1,$2e,$89,$3a,$ad
@ref24:
	.byte $00,$89,$24,$95,$28,$89,$2a,$a1,$32,$89
	.byte $ff,$06
	.word @ref21
	.byte $ff,$0a
	.word @ref22
	.byte $ff,$06
	.word @ref23
@ref28:
	.byte $00,$89,$24,$95,$28,$89,$2a,$a1,$32,$85,$2a,$81
@ref29:
	.byte $2e,$95,$24,$95,$22,$91,$19,$1a,$95
@ref30:
	.byte $00,$89,$24,$95,$28,$89,$2a,$95,$32,$91,$34,$81
@ref31:
	.byte $36,$9d,$2d,$2e,$85,$39,$3a,$89,$2d,$2f,$31,$32,$95
	.byte $ff,$0c
	.word @ref28
	.byte $ff,$09
	.word @ref29
	.byte $ff,$0c
	.word @ref30
	.byte $ff,$0d
	.word @ref31
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref36:
	.byte $88,$40,$89,$40,$89,$40,$89,$41,$41,$41,$40,$89,$40,$89,$40,$89
	.byte $41,$41,$40,$81
@ref37:
	.byte $40,$95,$40,$95,$40,$89,$40,$85,$41,$40,$85,$41,$41,$41,$40,$81
@ref38:
	.byte $40,$84,$25,$00,$83,$88,$40,$84,$25,$00,$83,$88,$40,$84,$25,$00
	.byte $83,$88,$40,$84,$24,$83,$29,$88,$40,$84,$2b,$00,$83,$88,$40,$84
	.byte $2b,$00,$83,$88,$40,$84,$2b,$00,$83,$88,$40,$84,$2a,$83,$32,$81
@ref39:
	.byte $88,$40,$84,$2f,$00,$83,$88,$40,$84,$2f,$00,$83,$88,$40,$84,$2f
	.byte $00,$83,$88,$40,$84,$34,$83,$2f,$88,$40,$84,$33,$00,$83,$88,$40
	.byte $84,$2f,$00,$83,$88,$40,$84,$2a,$8a,$58,$84,$2e,$8a,$58,$84,$2a
	.byte $88,$40,$84,$28,$8a,$58,$84,$2a,$8a,$58,$84,$28
@ref40:
	.byte $88,$40,$84,$25,$00,$83,$88,$40,$84,$25,$00,$83,$88,$40,$84,$25
	.byte $00,$83,$88,$40,$84,$24,$83,$29,$88,$40,$84,$2b,$00,$83,$88,$40
	.byte $84,$2b,$00,$83,$88,$40,$84,$2b,$00,$83,$88,$40,$84,$2a,$83,$32
	.byte $81
@ref41:
	.byte $88,$40,$84,$2f,$00,$83,$88,$40,$84,$2f,$00,$83,$88,$40,$84,$2f
	.byte $00,$83,$88,$40,$84,$34,$83,$2f,$88,$40,$84,$32,$83,$8a,$59,$88
	.byte $40,$84,$3a,$83,$8a,$59,$88,$40,$84,$40,$83,$8a,$59,$88,$40,$84
	.byte $46,$83,$80,$66,$8a,$70
	.byte $ff,$21
	.word @ref40
	.byte $ff,$24
	.word @ref39
	.byte $ff,$21
	.word @ref40
	.byte $ff,$21
	.word @ref41
	.byte $ff,$21
	.word @ref40
	.byte $ff,$24
	.word @ref39
	.byte $ff,$21
	.word @ref40
	.byte $ff,$21
	.word @ref41
	.byte $ff,$21
	.word @ref40
	.byte $ff,$24
	.word @ref39
	.byte $ff,$21
	.word @ref40
	.byte $ff,$21
	.word @ref41
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref54:
	.byte $8b,$8c,$14,$95,$14,$95,$14,$95,$14,$89
@ref55:
	.byte $8b,$14,$95,$14,$95,$14,$85,$14,$89,$86,$15,$8c,$14,$85,$86,$14
	.byte $8e,$10
	.byte $ff,$09
	.word @ref54
	.byte $ff,$0e
	.word @ref55
	.byte $ff,$09
	.word @ref54
	.byte $ff,$0e
	.word @ref55
	.byte $ff,$09
	.word @ref54
	.byte $ff,$0e
	.word @ref55
	.byte $ff,$09
	.word @ref54
	.byte $ff,$0e
	.word @ref55
@ref64:
	.byte $86,$1f,$1f,$1f,$8c,$15,$86,$1f,$1f,$1f,$1f,$1f,$8c,$15,$86,$1f
	.byte $1f,$1f,$1f,$1f,$8c,$15,$86,$1f,$1f,$1f,$1f,$1f,$8c,$15,$86,$1f
	.byte $1e,$81
@ref65:
	.byte $1f,$1f,$1f,$8c,$15,$86,$1f,$1f,$1f,$1f,$1f,$8c,$15,$86,$1f,$1f
	.byte $1f,$1f,$1f,$8c,$15,$86,$1f,$8c,$14,$86,$1e,$1f,$1f,$15,$8c,$15
	.byte $86,$1f,$14,$81
@ref66:
	.byte $83,$1d,$1d,$8c,$15,$86,$1d,$1c,$85,$1d,$1d,$8c,$15,$86,$03,$02
	.byte $85,$1d,$1d,$8c,$15,$86,$1d,$1c,$85,$1d,$1d,$8c,$15,$86,$03,$02
	.byte $81
@ref67:
	.byte $83,$1d,$1d,$8c,$15,$86,$1d,$1c,$85,$1d,$1d,$8c,$15,$86,$1d,$1c
	.byte $85,$1d,$1d,$03,$1d,$1d,$09,$0b,$0d,$0f,$11,$12,$81
@ref68:
	.byte $1f,$1f,$1f,$8c,$15,$86,$1f,$1f,$1f,$1f,$1f,$8c,$15,$86,$1f,$1f
	.byte $1f,$1f,$1f,$8c,$15,$86,$1f,$1f,$1f,$1f,$1f,$8c,$15,$86,$1f,$1e
	.byte $81
	.byte $ff,$1a
	.word @ref65
	.byte $ff,$19
	.word @ref66
	.byte $ff,$19
	.word @ref67
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref72:
	.byte $00,$dd
@ref73:
	.byte $df
@ref74:
	.byte $00,$dd
@ref75:
	.byte $df
@ref76:
	.byte $00,$dd
@ref77:
	.byte $df
@ref78:
	.byte $00,$dd
@ref79:
	.byte $df
@ref80:
	.byte $00,$dd
@ref81:
	.byte $df
@ref82:
	.byte $00,$dd
@ref83:
	.byte $df
@ref84:
	.byte $00,$dd
@ref85:
	.byte $df
@ref86:
	.byte $00,$dd
@ref87:
	.byte $df
@ref88:
	.byte $00,$dd
@ref89:
	.byte $df
	.byte $fd
	.word @song0ch4loop
