CC = zcc

CFLAGS = +zx -vn -I../Core/include -create-app -lndos -DAMALLOC -DRES64X128 -DSPECTRUM -Os -compiler=sdcc

all: derelict.tap

derelict.tap: src/demo.o src/spectrum.o ../core/src/Core.o ../core/src/Derelict.o
	$(CC) $(CFLAGS) -odemo.bin src/demo.o src/spectrum.o ../core/src/Core.o ../core/src/Derelict.o

clean:
	$(RM) *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.bin *.tap
	$(RM) ../core/src/*.o
