CFLAGS = -DMSDOS -DRES128X128 -I../core/include -DCAN_PICK_OBJECT_AT_ANY_DISTANCE -Os

CC = ia16-elf-gcc

LDFLAGS = -li86

OBJS = src/demo.o src/msdos.o ../core/src/Core.o ../core/src/Derelict.o

TARGET = derelict.com

$(TARGET):	$(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LDFLAGS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	$(RM) -f *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.rom
	$(RM) -f ../core/src/*.o src/*.o
	rm *~