CFLAGS = -DMSDOS -DRES128X128 -DSUPPORTS_HACKING_MINIGAME -I../core/include -DINCLUDE_ROOM_DESCRIPTIONS -DTRACE_OBJECTS_OVER_FLOOR -DCAN_PICK_OBJECT_AT_ANY_DISTANCE

CC = i386-pc-msdosdjgpp-gcc

OBJS = src/demo.o src/msdos.o ../core/src/Core.o ../core/src/Derelict.o src/HackingMinigame.o

TARGET = derelict.exe

$(TARGET):	$(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LDFLAGS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	$(RM) -f *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.rom
	$(RM) -f ../core/src/*.o src/*.o
	rm *~