CC = zcc

CFLAGS = \
        +cpc \
        -compiler=sdcc \
        -SO3 \
        --max-allocs-per-node200000 \
        --opt-code-speed \
        -pragma-define:CLIB_EXIT_STACK_SIZE=0 \
        -pragma-define:CRT_MODEL=2 \
        -Iinclude \
        -I../core/include \
        -I../common/include \
        -DXRES_FRAMEBUFFER=320 \
        -DYRES_FRAMEBUFFER=200 \
        -DCPC \
        -DCAN_PICK_OBJECT_AT_ANY_DISTANCE \
        -DSUPPORTS_HACKING_MINIGAME \
        -DSUPPORTS_ROOM_TRANSITION_ANIMATION \
        -DRLE_COMPRESSED_MAPS \
        -DEMBEDDED_DATA

TARGET = derelict.dsk

OBJS = \
    src/Engine3D.o \
    src/cpc.o \
    src/KeyboardUI.o \
    src/HackingMinigame.o \
    ../common/src/Common.o \
    ../core/src/Core.o \
    ../core/src/Derelict.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -subtype=dsk -create-app -o $(TARGET) $(OBJS) $(LDFLAGS)

clean:
	rm -f $(OBJS) $(TARGET)
	rm -f *.bin
	rm -f *~

