# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/monty/git/madame_y

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/monty/git/madame_y

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monty/git/madame_y/CMakeFiles /Users/monty/git/madame_y/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/monty/git/madame_y/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named madame_y

# Build rule for target.
madame_y: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 madame_y
.PHONY : madame_y

# fast build rule for target.
madame_y/fast:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/build
.PHONY : madame_y/fast

src/demo.o: src/demo.c.o

.PHONY : src/demo.o

# target to build an object file
src/demo.c.o:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/src/demo.c.o
.PHONY : src/demo.c.o

src/demo.i: src/demo.c.i

.PHONY : src/demo.i

# target to preprocess a source file
src/demo.c.i:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/src/demo.c.i
.PHONY : src/demo.c.i

src/demo.s: src/demo.c.s

.PHONY : src/demo.s

# target to generate assembly for a file
src/demo.c.s:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/src/demo.c.s
.PHONY : src/demo.c.s

src/sdl2.o: src/sdl2.c.o

.PHONY : src/sdl2.o

# target to build an object file
src/sdl2.c.o:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/src/sdl2.c.o
.PHONY : src/sdl2.c.o

src/sdl2.i: src/sdl2.c.i

.PHONY : src/sdl2.i

# target to preprocess a source file
src/sdl2.c.i:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/src/sdl2.c.i
.PHONY : src/sdl2.c.i

src/sdl2.s: src/sdl2.c.s

.PHONY : src/sdl2.s

# target to generate assembly for a file
src/sdl2.c.s:
	$(MAKE) -f CMakeFiles/madame_y.dir/build.make CMakeFiles/madame_y.dir/src/sdl2.c.s
.PHONY : src/sdl2.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... madame_y"
	@echo "... src/demo.o"
	@echo "... src/demo.i"
	@echo "... src/demo.s"
	@echo "... src/sdl2.o"
	@echo "... src/sdl2.i"
	@echo "... src/sdl2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

