CC = zcc

CFLAGS = +gb -create-app -DGB -DAMALLOC  -O0 -I../Core/include
LDFLAGS =  -lm -vn  -m --opt-code-speed=all -pragma-output:USING_amalloc

all: derelict.gb

derelict.gb: src/demo.o src/gb.o ../core/src/Derelict.o ../core/src/Core.o
	$(CC) $(CFLAGS) -o demo.gb src/demo.o src/gb.o ../core/src/Core.o ../core/src/Derelict.o $(LDFLAGS)

clean:
	$(RM) *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.rom *.gb src/*.o
	$(RM) ../core/src/*.o