name: Build ia16 package of the MY frontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: install ia16-gcc
      run: sudo apt-get update && sudo apt-get -y install software-properties-common && sudo add-apt-repository ppa:tkchia/build-ia16 && sudo apt-get install -y build-essential && sudo apt-get install -y gcc-ia16-elf
    - name: make
      run: cd my_frontend && make -f Makefile.ia16
