name: Run Core tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: make
      run: cd core && make
    - name: make check
      run: cd core && make check && export TEST_RESULTS=`./unittests`
    - name: Create Awesome Badge for failure
      uses: schneegans/dynamic-badges-action@v1.4.0
      if: ${{contains(env.TEST_RESULTS, 'FAILED'}}
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: d5c8f0e046da0ddc04c43cff251f661c
        filename: space-trashman-blues-tests.json
        label: Core tests
        message: failing
        color: orange
    - name: Create Awesome Badge for success
      uses: schneegans/dynamic-badges-action@v1.4.0
      if: ${{contains(env.TEST_RESULTS, 'FAILED'}}
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: d5c8f0e046da0ddc04c43cff251f661c
        filename: space-trashman-blues-tests.json
        label: Core tests
        message: passing
        color: green