name: Run Core tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: make
      run: cd core && make
    - name: make check
      run: cd core && make check
    - name: run coverage
      run: cd core && ./update-coverage.sh