name: publish docs for the CORE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive    
    - name: Install MKDocs
      run: pip install mkdocs
    - name: Install gcov and textinfo
      run: sudo apt-get install gcov textinfo
    - name: Generate HTML from game design markdown files
      run: cd core && mkdocs build
    - name: Generate text coverage report
      run: ./update-coverage.sh && mv coverage site
    - name: Deploy 	
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: core/site